# Generated by Django 5.0.7 on 2026-01-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_alter_driver_driver_photo_alter_driver_license_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='cr_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='or_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin_number',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
