# Generated by Django 5.0.7 on 2026-02-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0019_alter_driver_driver_photo_alter_vehicle_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_photo',
            field=models.ImageField(upload_to='driver_photos/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/qrcodes/'),
        ),
    ]
