# Generated by Django 5.0.7 on 2026-02-17 07:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0020_alter_driver_driver_photo_alter_vehicle_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='driver_photo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_code'),
        ),
    ]
